name: round linker test
on:
  issues:
    types: [opened]

jobs:
  apply_labels:
    runs-on: ubuntu-latest
    steps:
    - uses: AnturK/round_linker@master
      if: ${{ secrets.CompileChangelogs == true }}
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
